"""Analyze Stage-2 error sources on dev.

Error classes (per missed gold quad):
A. correct quad not generated by Stage-1
B. correct quad generated, but reranker ranked it below a wrong candidate
C. same (aspect, opinion) group exists, but wrong category/affective candidate wins
D. wrong pair beats correct pair in global ranking
E. decode / dedup / NMS caused the final error
"""

import os
import sys
import json
import argparse
from collections import defaultdict

import torch
import yaml
from torch.utils.data import DataLoader

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from bspar.config import BSPARConfig
from bspar.data.preprocessor import (
    load_data,
    build_category_map,
    get_categories_for_dataset,
    ID_TO_SENTIMENT,
)
from bspar.data.dataset import BSPARStage1Dataset, collate_stage1
from bspar.models.bspar_stage1 import BSPARStage1
from bspar.models.bspar_stage2 import BSPARStage2
from bspar.evaluation.metrics import compute_quad_f1
from bspar.utils.seed import set_seed


def load_config(path):
    with open(path, "r", encoding="utf-8") as f:
        cfg_dict = yaml.safe_load(f)
    cfg = BSPARConfig()
    for k, v in cfg_dict.items():
        if hasattr(cfg, k):
            setattr(cfg, k, v)
    cfg.__post_init__()
    return cfg, cfg_dict


def roc_auc_binary(scores, labels):
    pos = [(s, y) for s, y in zip(scores, labels) if y == 1]
    neg = [(s, y) for s, y in zip(scores, labels) if y == 0]
    n_pos = len(pos)
    n_neg = len(neg)
    if n_pos == 0 or n_neg == 0:
        return None

    sorted_pairs = sorted(zip(scores, labels), key=lambda x: x[0])
    rank_sum_pos = 0.0
    for rank, (_, y) in enumerate(sorted_pairs, start=1):
        if y == 1:
            rank_sum_pos += rank

    auc = (rank_sum_pos - n_pos * (n_pos + 1) / 2.0) / (n_pos * n_neg)
    return float(auc)


def pr_auc_binary(scores, labels):
    n_pos = int(sum(1 for y in labels if y == 1))
    if n_pos == 0:
        return None

    pairs = sorted(zip(scores, labels), key=lambda x: x[0], reverse=True)
    tp = 0
    fp = 0
    ap = 0.0
    prev_recall = 0.0

    for _, y in pairs:
        if y == 1:
            tp += 1
        else:
            fp += 1
        precision = tp / max(tp + fp, 1)
        recall = tp / n_pos
        ap += precision * (recall - prev_recall)
        prev_recall = recall

    return float(ap)


def mean_or_none(vals):
    if not vals:
        return None
    return float(sum(vals) / len(vals))


def median_or_none(vals):
    if not vals:
        return None
    s = sorted(vals)
    n = len(s)
    mid = n // 2
    if n % 2 == 1:
        return float(s[mid])
    return float((s[mid - 1] + s[mid]) / 2.0)


def normalize_aff(aff, task_type):
    if task_type == "asqp":
        if isinstance(aff, int):
            return ID_TO_SENTIMENT.get(aff, "NEU")
        return str(aff)
    if isinstance(aff, (tuple, list)) and len(aff) == 2:
        return (float(aff[0]), float(aff[1]))
    return aff


def cand_matches_gold_exact(cand, gold, id_to_cat, task_type):
    asp_match = (
        (cand["asp_span"] == (-1, -1) and gold.aspect.is_null)
        or (cand["asp_span"] == (gold.aspect.start, gold.aspect.end))
    )
    opn_match = (
        (cand["opn_span"] == (-1, -1) and gold.opinion.is_null)
        or (cand["opn_span"] == (gold.opinion.start, gold.opinion.end))
    )
    cat_match = id_to_cat.get(cand["category_id"]) == gold.category

    if task_type == "asqp":
        pred_sent = ID_TO_SENTIMENT.get(int(cand["affective"]), "NEU")
        aff_match = pred_sent == gold.sentiment
    else:
        v_pred, a_pred = cand["affective"]
        v_diff = abs(v_pred - (gold.valence or 0.0))
        a_diff = abs(a_pred - (gold.arousal or 0.0))
        aff_match = (v_diff < 0.5) and (a_diff < 0.5)

    return asp_match and opn_match and cat_match and aff_match


def cand_matches_gold_pair(cand, gold):
    asp_match = (
        (cand["asp_span"] == (-1, -1) and gold.aspect.is_null)
        or (cand["asp_span"] == (gold.aspect.start, gold.aspect.end))
    )
    opn_match = (
        (cand["opn_span"] == (-1, -1) and gold.opinion.is_null)
        or (cand["opn_span"] == (gold.opinion.start, gold.opinion.end))
    )
    return asp_match and opn_match


def decode_with_dedup(candidates, scores, max_pred=10):
    order = sorted(range(len(candidates)), key=lambda i: scores[i], reverse=True)
    selected = []
    selected_ids = []
    seen = set()
    for i in order:
        c = candidates[i]
        key = (tuple(c["asp_span"]), tuple(c["opn_span"]), int(c["category_id"]))
        if key in seen:
            continue
        seen.add(key)
        selected_ids.append(i)
        selected.append(c)
        if len(selected) >= max_pred:
            break
    return selected, selected_ids, order


def decode_no_dedup(candidates, scores, max_pred=10):
    order = sorted(range(len(candidates)), key=lambda i: scores[i], reverse=True)
    return [candidates[i] for i in order[:max_pred]], order[:max_pred], order


def candidate_to_simple(cand, score, id_to_cat, task_type, idx=None):
    return {
        "idx": idx,
        "asp_span": tuple(cand["asp_span"]),
        "opn_span": tuple(cand["opn_span"]),
        "category": id_to_cat.get(cand["category_id"], "UNK"),
        "affective": normalize_aff(cand["affective"], task_type),
        "score": float(score),
    }


def gold_to_simple(g):
    return {
        "asp_span": (-1, -1) if g.aspect.is_null else (g.aspect.start, g.aspect.end),
        "opn_span": (-1, -1) if g.opinion.is_null else (g.opinion.start, g.opinion.end),
        "category": g.category,
        "affective": g.sentiment if g.sentiment is not None else (g.valence, g.arousal),
    }


def pick_representatives(records, n=20):
    buckets = defaultdict(list)
    for r in records:
        buckets[r["error_type"]].append(r)

    out = []
    for cls in ["B", "C", "D", "E"]:
        out.extend(buckets[cls])
    if len(out) >= n:
        return out[:n]

    out.extend(buckets["A"][: (n - len(out))])
    return out[:n]


def main():
    parser = argparse.ArgumentParser(description="Analyze Stage-2 error sources")
    parser.add_argument("--config", required=True)
    parser.add_argument("--stage1_ckpt", required=True)
    parser.add_argument("--stage2_ckpt", required=True)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--max_pred", type=int, default=10)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    set_seed(args.seed)
    config, cfg_dict = load_config(args.config)

    dataset_name = cfg_dict.get("dataset_name", "asqp_rest15")
    data_format = cfg_dict.get("data_format", "auto")
    data_dir = cfg_dict.get("data_dir", "data/asqp_rest15")
    dev_file = os.path.join(data_dir, cfg_dict.get("dev_file", "dev.txt"))

    categories = get_categories_for_dataset(dataset_name)
    cat_to_id, id_to_cat = build_category_map(categories)
    config.num_categories = len(categories)

    dev_examples = load_data(dev_file, data_format, categories)
    dev_dataset = BSPARStage1Dataset(dev_examples, config.model_name)
    dev_loader = DataLoader(
        dev_dataset,
        batch_size=config.batch_size,
        shuffle=False,
        collate_fn=collate_stage1,
    )

    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    stage1 = BSPARStage1(config)
    ckpt1 = torch.load(args.stage1_ckpt, map_location=device, weights_only=False)
    stage1.load_state_dict(ckpt1["model_state_dict"], strict=False)
    stage1.to(device)
    stage1.eval()

    stage2 = BSPARStage2(config)
    ckpt2 = torch.load(args.stage2_ckpt, map_location=device, weights_only=False)
    stage2.load_state_dict(ckpt2["model_state_dict"], strict=False)
    stage2.to(device)
    stage2.eval()

    pair_thr = getattr(config, "stage1_pair_score_threshold", 0.01)
    pair_strategy = getattr(config, "stage1_pair_retention_strategy", "topn_only")
    pair_top_n = getattr(config, "stage1_pair_top_n", 20)

    all_preds = []
    all_golds = []

    errors = []
    error_counts = {"A": 0, "B": 0, "C": 0, "D": 0, "E": 0}
    total_gold = 0
    total_missed = 0

    # Pair-level metrics
    pair_final_scores = []
    pair_labels = []
    pair_prior_scores = []
    pair_prior_labels = []

    gold_pair_best_ranks_present = []
    gold_pair_present = 0
    gold_pair_missing = 0
    gold_pair_topk_hits_present = 0

    final_topk_pair_hits = 0
    final_topk_pair_total = 0

    ex_global_idx = 0

    with torch.no_grad():
        for batch in dev_loader:
            outputs = stage1(
                input_ids=batch["input_ids"].to(device),
                attention_mask=batch["attention_mask"].to(device),
                word_to_subword=batch["word_to_subword"],
                mode="inference",
                pair_score_threshold=pair_thr,
                pair_retention_strategy=pair_strategy,
                pair_top_n=pair_top_n,
            )

            batch_size = len(outputs["candidates"])
            for b in range(batch_size):
                candidates = outputs["candidates"][b]
                gold_quads = batch["gold_quads"][b]
                ex_obj = dev_examples[ex_global_idx]

                all_golds.append(gold_quads)
                total_gold += len(gold_quads)

                gold_pairs = set()
                for g in gold_quads:
                    a = (-1, -1) if g.aspect.is_null else (g.aspect.start, g.aspect.end)
                    o = (-1, -1) if g.opinion.is_null else (g.opinion.start, g.opinion.end)
                    gold_pairs.add((a, o))

                if not candidates:
                    all_preds.append([])
                    final_topk_pair_total += len(gold_pairs)
                    gold_pair_missing += len(gold_pairs)

                    for g in gold_quads:
                        total_missed += 1
                        error_counts["A"] += 1
                        errors.append({
                            "error_type": "A",
                            "example_id": ex_obj.id,
                            "example_index": ex_global_idx,
                            "text": ex_obj.text,
                            "gold": gold_to_simple(g),
                            "reason": "No Stage-1 candidates generated",
                            "best_exact_rank": None,
                            "best_exact_score": None,
                            "top10_no_dedup": [],
                            "final_preds": [],
                        })
                    ex_global_idx += 1
                    continue

                pair_reprs = torch.stack([c["pair_repr"] for c in candidates]).to(device)
                cat_ids = torch.tensor(
                    [c["category_id"] for c in candidates], dtype=torch.long, device=device
                )
                if config.task_type == "asqp":
                    aff_input = torch.tensor(
                        [c["affective"] for c in candidates], dtype=torch.long, device=device
                    )
                else:
                    aff_input = torch.tensor(
                        [c["affective"] for c in candidates], dtype=torch.float, device=device
                    )
                meta = torch.tensor(
                    [c["meta_features"] for c in candidates], dtype=torch.float, device=device
                )

                out2 = stage2(
                    pair_reprs=pair_reprs.unsqueeze(0),
                    cat_ids=cat_ids.unsqueeze(0),
                    aff_input=aff_input.unsqueeze(0),
                    meta_features=meta.unsqueeze(0),
                    mode="inference",
                )
                scores = out2["quad_scores"][0].detach().cpu().tolist()
                pair_prior_logits = None
                if "pair_prior_logits" in out2:
                    pair_prior_logits = out2["pair_prior_logits"][0].detach().cpu().tolist()

                final_pred_cands, final_pred_ids, sorted_ids = decode_with_dedup(
                    candidates, scores, max_pred=args.max_pred
                )
                _, nodp_ids, _ = decode_no_dedup(
                    candidates, scores, max_pred=args.max_pred
                )

                # Pair-level grouping and metrics.
                group_to_ids = {}
                for i, c in enumerate(candidates):
                    key = (tuple(c["asp_span"]), tuple(c["opn_span"]))
                    if key not in group_to_ids:
                        group_to_ids[key] = []
                    group_to_ids[key].append(i)

                for pair_key, ids in group_to_ids.items():
                    label = 1 if pair_key in gold_pairs else 0
                    score_group = max(scores[i] for i in ids)
                    pair_final_scores.append(float(score_group))
                    pair_labels.append(label)

                    if pair_prior_logits is not None and getattr(config, "stage2_use_pair_prior", False):
                        prior_group = max(pair_prior_logits[i] for i in ids)
                        pair_prior_scores.append(float(prior_group))
                        pair_prior_labels.append(label)

                # Gold pair global rank (best rank over candidates sharing pair).
                for gp in gold_pairs:
                    if gp in group_to_ids:
                        gold_pair_present += 1
                        best_rank = min(sorted_ids.index(i) + 1 for i in group_to_ids[gp])
                        gold_pair_best_ranks_present.append(best_rank)
                        if best_rank <= args.max_pred:
                            gold_pair_topk_hits_present += 1
                    else:
                        gold_pair_missing += 1

                final_pair_set = set(
                    (tuple(candidates[i]["asp_span"]), tuple(candidates[i]["opn_span"]))
                    for i in final_pred_ids
                )
                final_topk_pair_hits += len(gold_pairs & final_pair_set)
                final_topk_pair_total += len(gold_pairs)

                pred_dicts = []
                for i in final_pred_ids:
                    c = candidates[i]
                    pred_dicts.append({
                        "asp_span": tuple(c["asp_span"]),
                        "opn_span": tuple(c["opn_span"]),
                        "category_id": int(c["category_id"]),
                        "affective": int(c["affective"]) if isinstance(c["affective"], int) else c["affective"],
                        "pair_score": float(scores[i]),
                        "cat_prob": float(c.get("cat_prob", 0.0)),
                    })
                all_preds.append(pred_dicts)

                # Per-gold miss classification.
                for g in gold_quads:
                    in_final = any(
                        cand_matches_gold_exact(candidates[i], g, id_to_cat, config.task_type)
                        for i in final_pred_ids
                    )
                    if in_final:
                        continue

                    total_missed += 1

                    exact_ids = [
                        i for i, c in enumerate(candidates)
                        if cand_matches_gold_exact(c, g, id_to_cat, config.task_type)
                    ]

                    reason = ""
                    etype = "B"
                    best_exact_rank = None
                    best_exact_score = None

                    if not exact_ids:
                        etype = "A"
                        reason = "Gold quad not generated by Stage-1 candidates"
                    else:
                        best_exact = max(exact_ids, key=lambda i: scores[i])
                        best_exact_score = float(scores[best_exact])
                        best_exact_rank = sorted_ids.index(best_exact) + 1

                        if (best_exact in nodp_ids) and (best_exact not in final_pred_ids):
                            etype = "E"
                            reason = "Would be in top-K without dedup; dropped by decode dedup"
                        else:
                            pair_ids = [i for i, c in enumerate(candidates) if cand_matches_gold_pair(c, g)]
                            if pair_ids:
                                best_pair = max(pair_ids, key=lambda i: scores[i])
                                best_pair_is_exact = cand_matches_gold_exact(
                                    candidates[best_pair], g, id_to_cat, config.task_type
                                )
                                if (not best_pair_is_exact) and (scores[best_pair] > scores[best_exact]):
                                    etype = "C"
                                    reason = (
                                        "Same (aspect,opinion) group exists but wrong "
                                        "category/affective candidate scores higher"
                                    )
                                else:
                                    if best_exact_rank is not None and best_exact_rank > args.max_pred:
                                        topk_wrong_pair = any(
                                            not cand_matches_gold_pair(candidates[i], g)
                                            for i in nodp_ids
                                        )
                                        if topk_wrong_pair:
                                            etype = "D"
                                            reason = "Wrong pair candidates outrank correct pair globally"
                                        else:
                                            etype = "B"
                                            reason = "Generated, but reranker rank still loses to wrong candidate"
                                    else:
                                        etype = "B"
                                        reason = "Generated, but reranker rank still loses to wrong candidate"
                            else:
                                etype = "B"
                                reason = "Generated exact quad, but no pair-group trace found"

                    error_counts[etype] += 1

                    top10_dump = [
                        candidate_to_simple(candidates[i], scores[i], id_to_cat, config.task_type, idx=i)
                        for i in nodp_ids[:10]
                    ]
                    final_dump = [
                        candidate_to_simple(candidates[i], scores[i], id_to_cat, config.task_type, idx=i)
                        for i in final_pred_ids
                    ]

                    errors.append({
                        "error_type": etype,
                        "example_id": ex_obj.id,
                        "example_index": ex_global_idx,
                        "text": ex_obj.text,
                        "gold": gold_to_simple(g),
                        "reason": reason,
                        "best_exact_rank": best_exact_rank,
                        "best_exact_score": best_exact_score,
                        "top10_no_dedup": top10_dump,
                        "final_preds": final_dump,
                    })

                ex_global_idx += 1

    metrics = compute_quad_f1(all_preds, all_golds, id_to_cat, cat_to_id)
    reps = pick_representatives(errors, n=20)

    pair_prior_auc = roc_auc_binary(pair_prior_scores, pair_prior_labels)
    pair_prior_pr_auc = pr_auc_binary(pair_prior_scores, pair_prior_labels)
    pair_final_auc = roc_auc_binary(pair_final_scores, pair_labels)
    pair_final_pr_auc = pr_auc_binary(pair_final_scores, pair_labels)

    out = {
        "config": args.config,
        "stage1_ckpt": args.stage1_ckpt,
        "stage2_ckpt": args.stage2_ckpt,
        "dev_examples": len(all_golds),
        "quad_f1": float(metrics["quad_f1"]),
        "span_f1": float(metrics["span_f1"]),
        "total_gold": total_gold,
        "total_missed_gold": total_missed,
        "error_counts": error_counts,
        "error_ratios_over_missed": {
            k: (error_counts[k] / total_missed if total_missed > 0 else 0.0)
            for k in ["A", "B", "C", "D", "E"]
        },
        "error_ratios_over_gold": {
            k: (error_counts[k] / total_gold if total_gold > 0 else 0.0)
            for k in ["A", "B", "C", "D", "E"]
        },
        "d_error_count": int(error_counts["D"]),
        "d_error_ratio_over_missed": (
            error_counts["D"] / total_missed if total_missed > 0 else 0.0
        ),
        "gold_pair_global_rank": {
            "present_count": int(gold_pair_present),
            "missing_count": int(gold_pair_missing),
            "mean_best_rank_present": mean_or_none(gold_pair_best_ranks_present),
            "median_best_rank_present": median_or_none(gold_pair_best_ranks_present),
            "topk_hit_ratio_present": (
                gold_pair_topk_hits_present / gold_pair_present if gold_pair_present > 0 else 0.0
            ),
        },
        "final_topk_correct_pair_coverage": (
            final_topk_pair_hits / final_topk_pair_total if final_topk_pair_total > 0 else 0.0
        ),
        "pair_prior_metrics": {
            "enabled": bool(getattr(config, "stage2_use_pair_prior", False)),
            "num_pairs": len(pair_prior_labels),
            "auc": pair_prior_auc,
            "pr_auc": pair_prior_pr_auc,
        },
        "pair_level_from_final_score": {
            "num_pairs": len(pair_labels),
            "auc": pair_final_auc,
            "pr_auc": pair_final_pr_auc,
        },
        "representative_examples": reps,
    }

    os.makedirs(os.path.dirname(args.output), exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        json.dump(out, f, indent=2, ensure_ascii=False)

    print(json.dumps({
        "quad_f1": out["quad_f1"],
        "span_f1": out["span_f1"],
        "total_gold": total_gold,
        "total_missed_gold": total_missed,
        "error_counts": error_counts,
        "d_error_ratio_over_missed": out["d_error_ratio_over_missed"],
        "gold_pair_global_rank": out["gold_pair_global_rank"],
        "final_topk_correct_pair_coverage": out["final_topk_correct_pair_coverage"],
        "pair_prior_metrics": out["pair_prior_metrics"],
        "output": args.output,
    }, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
